language: node_js

node_js:
  - "8.12"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

script:
  - npm test
  - npm build

deploy:
  provider: pages
  github-token: $GITHUB_KEY
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master
